Fix building with LTO on Linux
This fixes the following build failure
when building with CFLAGS="-flto" on Linux

/usr/bin/ld: /tmp/cc9dX2xq.ltrans2.ltrans.o: undefined reference to symbol 'ceil@@GLIBC_2.2.5'
/usr/bin/ld: /usr/lib/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

Signed-off-by: Kostadin Shishmanov <kocelfc@tutanota.com>