Check for pthread library and include it
This is to avoid the following problem:

-----8<-----
libtool: link: x86_64-pc-linux-gnu-gcc -D_LARGE_FILES=1 -I/usr/include/libusb-1.0 -I/usr/lib64/libzip/include -Os -pipe -march=bonnell -mmmx -mno-3dnow -msse -msse2 -msse3 -mssse3 --param l1-cache-size=24 --param l1-cache-line-size=64 --param l2-cache-size=512 -mtune=bonnell -Wl,-O1 -o idevicerestore idevicerestore-idevicerestore.o idevicerestore-common.o idevicerestore-tss.o idevicerestore-fls.o idevicerestore-mbn.o idevicerestore-img3.o idevicerestore-img4.o idevicerestore-ipsw.o idevicerestore-normal.o idevicerestore-dfu.o idevicerestore-recovery.o idevicerestore-restore.o idevicerestore-asr.o idevicerestore-fdr.o idevicerestore-limera1n.o idevicerestore-download.o idevicerestore-locking.o idevicerestore-socket.o idevicerestore-thread.o  /usr/lib64/libirecovery.so -lusb-1.0 -limobiledevice -lplist -lzip -lbz2 -lz -lssl -lcrypto -lcurl -Wl,--as-needed
idevicerestore-idevicerestore.o: In function `idevicerestore_start':
idevicerestore.c:(.text+0x3128): warning: the use of `tempnam' is dangerous, better use `mkstemp'
/usr/lib/gcc/x86_64-pc-linux-gnu/6.4.0/../../../../x86_64-pc-linux-gnu/bin/ld: idevicerestore-thread.o: undefined reference to symbol 'pthread_once@@GLIBC_2.2.5'
/lib64/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:451: idevicerestore] Error 1